spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: 123456


#spring.datasource.url=jdbc:postgresql://localhost:5432/tasks
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.datasource.driver-class-name=org.postgresql.Driver

#
#    spring.datasource.url=jdbc:postgresql://localhost:5432/tasks
#    spring.datasource.username=postgres
#    spring.datasource.password=123456
#
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#    spring.jpa.generate-ddl=false
#    spring.jpa.show-sql=true
#    spring.jpa.hibernate.ddl-auto=validate
#    hibernate.jdbc.lob.non_contextual_creation=false
#    spring.flyway.enabled=false
#
#
#
