drop TABLE if exists users;

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);


INSERT INTO users (id, email, password)
VALUES (1, 'alice@example.com', 'secret1');
INSERT INTO users (id, email, password)
VALUES (2, 'bob@example.com', 'secret2');

-- CREATE INDEX idx_tasks_title ON tasks (title);
--
-- CREATE INDEX idx_users_email ON users (email);
--
-- CREATE INDEX idx_users_password ON users (password);
--
-- ALTER TABLE tasks
--     ADD CONSTRAINT FK_TASKS_USER FOREIGN KEY (user_id) REFERENCES users (id);


--
-- INSERT INTO tasks (id, title, description, modified_at, is_done, user_id)
-- VALUES (1, 'Buy milk', '2 liters of milk', CURRENT_TIMESTAMP(), FALSE, 1),
--        (2, 'Write report', 'Finish quarterly report', CURRENT_TIMESTAMP(), TRUE, 2);
