
CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024),
    modified_at TIMESTAMP,
    is_done     BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

CREATE INDEX idx_tasks_title ON tasks (title);

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_users_password ON users (password);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_USER FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO users (id, email, password) VALUES (1, 'alice@example.com', 'secret1');
INSERT INTO users (id, email, password) VALUES (2, 'bob@example.com', 'secret2');

INSERT INTO tasks (id, title, description, modified_at, is_done, user_id) VALUES
  (1, 'Buy milk', '2 liters of milk', CURRENT_TIMESTAMP(), FALSE, 1),
  (2, 'Write report', 'Finish quarterly report', CURRENT_TIMESTAMP(), TRUE, 2);
