CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024),
    modified_at TIMESTAMP,
    is_done     BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

CREATE INDEX idx_tasks_title ON tasks (title);

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_users_password ON users (password);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_USER FOREIGN KEY (user_id) REFERENCES users (id);